robot_base_frame: base_link
update_frequency: 4.0
publish_frequency: 4.0

resolution: 0.05

obstacle_range: 5.5
raytrace_range: 6.0
footprint: [[1.11,0.50], [-1.40,0.50], [-1.40,-0.50], [1.11,-0.50]]
inflation_radius: 1


observation_sources: laser_scan_sensor 

laser_scan_sensor: {sensor_frame: laser_link, data_type: LaserScan, topic: robot/scan, marking: true, clearing: true}
