#obstacle_range: 2.5
#raytrace_range: 3.0
#footprint: [[-0.5, -0.36], [-0.5, 0.36], [0.5, 0.36], [0.5, -0.36]] #footprint dovremmo mettere l'area del robot, per esempio ricompre un'area di 1 mt x 1 mt
#inflation_radius: 0.55 
#il robot tratterà tutti i percorsi che si trovano a 0,55 metri o più dagli ostacoli 
#come aventi lo stesso costo per gli ostacoli

#static:
#    map_topic: /map
#   subscribe_to_updates: true
    
#observation_sources: laser_scan_sensor 

#laser_scan_sensor: {sensor_frame: laser_link, data_type: LaserScan, topic: /robot/scan, marking: true, clearing: true}

footprint: [[-0.5, -0.36], [-0.5, 0.36], [0.5, 0.36], [0.5, -0.36]]
footprint_padding: 0.01

robot_base_frame: base_link
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 5.5
raytrace_range: 6.0

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser
    laser: {sensor_frame: laser_link, data_type: LaserScan, clearing: true, marking: true, topic: /robot/scan, inf_is_valid: true}

inflation:
    inflation_radius: 1.0