#local_costmap:
 # global_frame: odom
 # robot_base_frame: base_link
 # update_frequency: 5.0
 # publish_frequency: 2.0
 # static_map: true
 # rolling_window: true
 # width: 20.0
 # height: 20.0
 # resolution: 0.05

global_frame: odom
rolling_window: true

plugins:
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}